#!/usr/bin/env python3
"""Generate strict Pydantic v2 models from a neuralos-data profile.

Reads profile.json (emitted by profile_data.py) and writes models.py with one
model per table (databases) or per record shape (files / log templates). Every
field carries constraints derived from observed data: ranges from min/max,
patterns from log templates, Literal unions from low-cardinality strings,
Optional where nulls occur, and datetime parsing validators.

Usage:
  python gen_pydantic.py --profile profile.json --out models.py [--table NAME] [--model-name Transaction]
"""

import argparse
import os
import json
import re
from datetime import datetime, timezone

DT_FORMATS = [
    "%Y-%m-%dT%H:%M:%S.%f%z", "%Y-%m-%dT%H:%M:%S%z",
    "%Y-%m-%dT%H:%M:%S.%f", "%Y-%m-%dT%H:%M:%S",
    "%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d",
    "%d/%m/%Y %H:%M:%S", "%m/%d/%Y %H:%M:%S", "%d/%m/%Y", "%m/%d/%Y",
    "%H:%M:%S",
]

HEADER = '''"""Auto-generated by neuralos-data — strict models for the profiled source.

Source : {source}
Profiled at {profiled_at}
Sample : {sample_note}

Edit freely: the generator captured types and ranges from observed data, but
only you know what the fields MEAN. Add labels, rename cryptic columns, and
tighten or relax constraints as the domain requires.
"""
from __future__ import annotations

import re
from datetime import datetime, date
from typing import Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator

DT_FORMATS = {dt_formats!r}


def _parse_dt(value: Any) -> Any:
    """Accept several observed datetime spellings; pass through non-strings."""
    if isinstance(value, datetime) or not isinstance(value, str):
        return value
    for fmt in DT_FORMATS:
        try:
            return datetime.strptime(value.strip(), fmt)
        except ValueError:
            continue
    raise ValueError(f"unrecognized datetime spelling: {{value!r}}")


def _snake(name: str) -> str:
    if name.startswith("@"):
        name = "at_" + name[1:]
    name = re.sub(r"[^0-9a-zA-Z_]+", "_", name).strip("_")
    if not name:
        name = "field"
    if name[0].isdigit():
        name = "f_" + name
    return name.lower()
'''


def pascal(name):
    parts = re.split(r"[^0-9a-zA-Z]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p) or "Record"


def _snake(name):
    if name.startswith("@"):
        name = "at_" + name[1:]
    name = re.sub(r"[^0-9a-zA-Z_]+", "_", name).strip("_")
    if not name:
        name = "field"
    if name[0].isdigit():
        name = "f_" + name
    return name.lower()


def fmt_num(v):
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    return str(v)


def field_line(fname, f, indent="    "):
    """Return the Python field declaration for one profiled field."""
    py = f.get("python_type", "str")
    name = _snake(fname)
    kwargs, descs = [], [f"observed type: {f.get('detected_type', '?')}"]
    if f.get("db_type"):
        descs.append(f"db type: {f['db_type']}")
    if f.get("nullable"):
        kwargs.append("default=None")
    if f.get("regex"):
        kwargs.append(f'pattern=r"{f["regex"]}"')
    else:
        if "min" in f and "max" in f:
            kwargs.append(f"ge={fmt_num(f['min'])}")
            kwargs.append(f"le={fmt_num(f['max'])}")
        if "min_len" in f and "max_len" in f:
            kwargs.append(f"min_length={f['min_len']}")
            kwargs.append(f"max_length={f['max_len']}")
    if f.get("enum_values"):
        vals = ", ".join(json.dumps(v) for v in f["enum_values"])
        if len(vals) < 320:
            py = f"Literal[{vals}]"
            descs.append(f"all {f['distinct']} distinct values captured")
        else:
            descs.append(f"{f['distinct']} distinct values — too varied for Literal, "
                         f"e.g. {json.dumps(str(f['sample_values'][0])[:80]) if f.get('sample_values') else '?'}")
            py = "str"
    elif f.get("sample_values") and py == "str":
        ex = ", ".join(json.dumps(v) for v in f["sample_values"][:3])
        descs.append(f"e.g. {ex}")
    if f.get("null_count"):
        descs.append(f"{f['null_count']}/{f['sample_count']} sampled values were null")
    desc = "; ".join(descs).replace('"', "'")
    if len(desc) > 300:
        desc = desc[:297] + "..."
    if f.get("nullable") and not py.startswith("Optional["):
        # Nulls observed in data — the annotation itself must accept None,
        # not just the default (Pydantic v2 validates explicit null inputs).
        py = f"Optional[{py}]"
    if py.startswith("Optional[") and "default=None" not in kwargs:
        kwargs.append("default=None")
    base = py
    line = f"{name}: {base}"
    if kwargs:
        line += f" = Field({', '.join(kwargs)})"
    if f.get("detected_type") == "datetime":
        line += "\n" + indent  # validator appended separately
    return name, line


def datetime_validator(names, indent="    "):
    if not names:
        return ""
    joined = ", ".join(f'"{n}"' for n in names)
    return (f"{indent}@field_validator({joined}, mode=\"before\")\n"
            f"{indent}def _parse_datetime(cls, value):\n"
            f"{indent}    return _parse_dt(value)\n")


def model_for(name, fields, sample_note, doc_extra=""):
    lines = [f"class {name}(BaseModel):", f'    """{sample_note}{doc_extra}"""',
             '    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)', ""]
    dt_names = []
    used = set()
    body = []
    for f in fields:
        fname, line = field_line(f["name"], f)
        while fname in used:
            fname = fname + "_"
        used.add(fname)
        if f.get("detected_type") == "datetime":
            dt_names.append(fname)
        body.append(line)
    if not body:
        body = ["pass"]
    lines.extend("    " + b if b else "" for b in body)
    val = datetime_validator(dt_names)
    if val:
        lines.append(val.rstrip("\n"))
    return "\n".join(lines) + "\n"


def log_models(templates):
    out = ["", "# ---- log line templates ----",
           "import re as _re", "",
           "class LogLine(BaseModel):",
           '    """One parsed log line; the template that matched is recorded."""',
           '    model_config = ConfigDict(extra="forbid")', "",
           '    template: str = Field(..., description="name of the matching template")']
    compiled = ["TEMPLATES = []"]
    for i, t in enumerate(templates):
        cname = f"Template{i}Line"
        rx = t["regex"]
        if len(rx) > 400:
            rx = rx[:397] + "...)"
        out.append(f"class {cname}(BaseModel):")
        out.append(f'    """Matches ~{t["line_count"]} sampled lines. Example: {t["example"][:140]}"""')
        out.append('    model_config = ConfigDict(extra="forbid")')
        if t["fields"]:
            for fname in t["fields"]:
                out.append(f"    {_snake(fname)}: str")
        else:
            out.append("    raw: str")
        out.append("")
        compiled.append(
            f'TEMPLATES.append((\"{cname}\", _re.compile(r\"{rx}\"), {cname}))')
    out.extend(compiled)
    out.extend([
        "", "def parse_line(line: str) -> \"LogLine | None\":",
        "    \"\"\"Try every template; return a typed record or None.\"\"\"",
        "    for name, rx, model in TEMPLATES:",
        "        m = rx.match(line)",
        "        if m:",
        "            return model(**m.groupdict())",
        "    return None",
    ])
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--profile", default="profile.json")
    ap.add_argument("--out", default="models.py")
    ap.add_argument("--table", help="database table to model (default: first/all)")
    ap.add_argument("--model-name", help="model class name for file sources")
    ap.add_argument("--max-models", type=int, default=8)
    args = ap.parse_args()

    profile = json.load(open(args.profile, encoding="utf-8"))
    src = profile["source"]
    loc = src.get("location", "")
    if (src.get("kind") not in ("database",) and os.path.exists(loc)
            and os.path.getmtime(loc) > os.path.getmtime(args.profile)):
        print(f"WARNING: {loc} is newer than {args.profile} — re-profile before "
              "trusting this model (python3 profile_data.py --source ...)")
    kind = src.get("kind")
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    header = HEADER.format(source=src.get("location", "?"), profiled_at=now,
                           sample_note="generated from profiled sample data",
                           dt_formats=DT_FORMATS)

    blocks = []
    if kind == "database":
        tables = src.get("tables", [])
        chosen = [t for t in tables if not args.table or t["name"] == args.table] or tables
        for t in chosen[:args.max_models]:
            note = (f"{len(t['columns'])} columns; {t.get('db_row_count', '?')} rows in source. ")
            blocks.append(model_for(pascal(t["name"]), t["columns"], note))
        if len(chosen) > args.max_models:
            header += (f"\n# NOTE: {len(chosen)} tables profiled; generated the first "
                       f"{args.max_models}. Re-run with --table for the rest.")
    elif kind == "log_lines":
        name = args.model_name or "Record"
        blocks.append(model_for(name, profile.get("fields", []),
                                f"{len(profile.get('sample_records', []))} lines sampled. "))
        blocks.append(log_models(profile.get("log_templates", [])))
    else:
        name = args.model_name or pascal(src.get("location", "record").split("/")[-1].split(".")[0])
        blocks.append(model_for(name, profile.get("fields", []),
                                f"{len(profile.get('sample_records', []))} records sampled. "))

    content = header + "\n\n" + "\n\n".join(b for b in blocks if b.strip()) + "\n"
    open(args.out, "w", encoding="utf-8").write(content)
    n_models = content.count("class ")
    print(f"models written: {args.out} ({n_models} classes, {kind} profile)")


if __name__ == "__main__":
    main()
